model:
  type: segment_full_song
  max_tokens: 950
  pitch_range: [21, 109]
  max_note_duration: 64
  dim: 512
  encoder_num_layers: 4
  decoder_num_layers: 8
  max_forward_duration: 256
  max_song_duration: 6400
  max_context_duration:
    left: 256
    right: 256
    seed: 256
    reference: 256
    target: 256
  latent_dim: 256
  frames_per_bar: 32
  bar_embedder:
    type: vae
    duration: 32
    test_duration: 256
    max_tokens: 160
    pitch_range: [21, 109]
    max_note_duration: 64
    encoder:
      dim: 512
      num_layers: 5
    decoder:
      dim: 512
      num_layers: 5
    bottleneck:
      type: "vae"
      vae_params:
        beta: 0.1
        latent_dim: 256
        beta_cycle_steps: 50000
        beta_start_step: 1000

training:
  seed: 0x517
  batch_size: 6
  accum_batches: 1
  shuffle: true
  drop_last: true
  gradient_clip_val: null
  precision: "16-mixed"
  demo_samples: 1

  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0
  lr_scheduler:
    gamma: 0.999998502134985 # 0.05 at 2m steps

  demo_steps: 4000
  checkpoint_steps: 50000
  max_steps: 2000000
